package escola.entity;
// Generated Apr 7, 2019 5:26:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlunoLingua generated by hbm2java
 */
public class AlunoLingua  implements java.io.Serializable {


     private Integer id;
     private Linguas linguas;
     private Usuarios usuarios;
     private int nivel;
     private Set alunosTurmas = new HashSet(0);

    public AlunoLingua() {
    }

	
    public AlunoLingua(Linguas linguas, Usuarios usuarios, int nivel) {
        this.linguas = linguas;
        this.usuarios = usuarios;
        this.nivel = nivel;
    }
    public AlunoLingua(Linguas linguas, Usuarios usuarios, int nivel, Set alunosTurmas) {
       this.linguas = linguas;
       this.usuarios = usuarios;
       this.nivel = nivel;
       this.alunosTurmas = alunosTurmas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Linguas getLinguas() {
        return this.linguas;
    }
    
    public void setLinguas(Linguas linguas) {
        this.linguas = linguas;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }
    public Set getAlunosTurmas() {
        return this.alunosTurmas;
    }
    
    public void setAlunosTurmas(Set alunosTurmas) {
        this.alunosTurmas = alunosTurmas;
    }




}


