package escola.entity;
// Generated Apr 7, 2019 7:04:34 PM by Hibernate Tools 4.3.1



/**
 * AlunosTurma generated by hbm2java
 */
public class AlunosTurma  implements java.io.Serializable {


     private Integer id;
     private AlunoLingua alunoLingua;
     private Turma turma;

    public AlunosTurma() {
    }

    public AlunosTurma(AlunoLingua alunoLingua, Turma turma) {
       this.alunoLingua = alunoLingua;
       this.turma = turma;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AlunoLingua getAlunoLingua() {
        return this.alunoLingua;
    }
    
    public void setAlunoLingua(AlunoLingua alunoLingua) {
        this.alunoLingua = alunoLingua;
    }
    public Turma getTurma() {
        return this.turma;
    }
    
    public void setTurma(Turma turma) {
        this.turma = turma;
    }




}


