package escola.entity;
// Generated Apr 7, 2019 7:04:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlunoLingua generated by hbm2java
 */
public class AlunoLingua  implements java.io.Serializable {


     private Integer id;
     private Lingua lingua;
     private Usuario usuario;
     private int nivel;
     private Set alunosTurmas = new HashSet(0);

    public AlunoLingua() {
    }

	
    public AlunoLingua(Lingua lingua, Usuario usuario, int nivel) {
        this.lingua = lingua;
        this.usuario = usuario;
        this.nivel = nivel;
    }
    public AlunoLingua(Lingua lingua, Usuario usuario, int nivel, Set alunosTurmas) {
       this.lingua = lingua;
       this.usuario = usuario;
       this.nivel = nivel;
       this.alunosTurmas = alunosTurmas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Lingua getLingua() {
        return this.lingua;
    }
    
    public void setLingua(Lingua lingua) {
        this.lingua = lingua;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }
    public Set getAlunosTurmas() {
        return this.alunosTurmas;
    }
    
    public void setAlunosTurmas(Set alunosTurmas) {
        this.alunosTurmas = alunosTurmas;
    }




}


