package escola.entity;
// Generated Apr 7, 2019 5:26:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Linguas generated by hbm2java
 */
public class Linguas  implements java.io.Serializable {


     private Integer id;
     private String dsNome;
     private Set turmas = new HashSet(0);
     private Set alunoLinguas = new HashSet(0);
     private Set professorLinguas = new HashSet(0);

    public Linguas() {
    }

    public Linguas(String dsNome, Set turmas, Set alunoLinguas, Set professorLinguas) {
       this.dsNome = dsNome;
       this.turmas = turmas;
       this.alunoLinguas = alunoLinguas;
       this.professorLinguas = professorLinguas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDsNome() {
        return this.dsNome;
    }
    
    public void setDsNome(String dsNome) {
        this.dsNome = dsNome;
    }
    public Set getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set turmas) {
        this.turmas = turmas;
    }
    public Set getAlunoLinguas() {
        return this.alunoLinguas;
    }
    
    public void setAlunoLinguas(Set alunoLinguas) {
        this.alunoLinguas = alunoLinguas;
    }
    public Set getProfessorLinguas() {
        return this.professorLinguas;
    }
    
    public void setProfessorLinguas(Set professorLinguas) {
        this.professorLinguas = professorLinguas;
    }




}


