package escola.entity;
// Generated Apr 7, 2019 5:26:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProfessorLingua generated by hbm2java
 */
public class ProfessorLingua  implements java.io.Serializable {


     private Integer id;
     private Linguas linguas;
     private Usuarios usuarios;
     private Integer nivel;
     private Set turmas = new HashSet(0);

    public ProfessorLingua() {
    }

	
    public ProfessorLingua(Linguas linguas, Usuarios usuarios) {
        this.linguas = linguas;
        this.usuarios = usuarios;
    }
    public ProfessorLingua(Linguas linguas, Usuarios usuarios, Integer nivel, Set turmas) {
       this.linguas = linguas;
       this.usuarios = usuarios;
       this.nivel = nivel;
       this.turmas = turmas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Linguas getLinguas() {
        return this.linguas;
    }
    
    public void setLinguas(Linguas linguas) {
        this.linguas = linguas;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Integer getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
    public Set getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set turmas) {
        this.turmas = turmas;
    }




}


