package escola.entity;
// Generated Apr 7, 2019 7:04:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProfessorLingua generated by hbm2java
 */
public class ProfessorLingua  implements java.io.Serializable {


     private Integer id;
     private Lingua lingua;
     private Usuario usuario;
     private Integer nivel;
     private Set turmas = new HashSet(0);

    public ProfessorLingua() {
    }

	
    public ProfessorLingua(Lingua lingua, Usuario usuario) {
        this.lingua = lingua;
        this.usuario = usuario;
    }
    public ProfessorLingua(Lingua lingua, Usuario usuario, Integer nivel, Set turmas) {
       this.lingua = lingua;
       this.usuario = usuario;
       this.nivel = nivel;
       this.turmas = turmas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Lingua getLingua() {
        return this.lingua;
    }
    
    public void setLingua(Lingua lingua) {
        this.lingua = lingua;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
    public Set getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set turmas) {
        this.turmas = turmas;
    }




}


