package escola.entity;
// Generated Apr 7, 2019 5:26:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Turma generated by hbm2java
 */
public class Turma  implements java.io.Serializable {


     private Integer id;
     private Linguas linguas;
     private ProfessorLingua professorLingua;
     private Date horario;
     private Integer nivel;
     private Set alunosTurmas = new HashSet(0);

    public Turma() {
    }

	
    public Turma(Linguas linguas, ProfessorLingua professorLingua) {
        this.linguas = linguas;
        this.professorLingua = professorLingua;
    }
    public Turma(Linguas linguas, ProfessorLingua professorLingua, Date horario, Integer nivel, Set alunosTurmas) {
       this.linguas = linguas;
       this.professorLingua = professorLingua;
       this.horario = horario;
       this.nivel = nivel;
       this.alunosTurmas = alunosTurmas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Linguas getLinguas() {
        return this.linguas;
    }
    
    public void setLinguas(Linguas linguas) {
        this.linguas = linguas;
    }
    public ProfessorLingua getProfessorLingua() {
        return this.professorLingua;
    }
    
    public void setProfessorLingua(ProfessorLingua professorLingua) {
        this.professorLingua = professorLingua;
    }
    public Date getHorario() {
        return this.horario;
    }
    
    public void setHorario(Date horario) {
        this.horario = horario;
    }
    public Integer getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
    public Set getAlunosTurmas() {
        return this.alunosTurmas;
    }
    
    public void setAlunosTurmas(Set alunosTurmas) {
        this.alunosTurmas = alunosTurmas;
    }




}


