package escola.entity;
// Generated Jun 17, 2009 11:42:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Actor generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Short id;
     private String nome;
     private int cpf;
     private int rg;
     private String senha;
     private String endereco;
     private Date dt_nascimento;

    public Usuario(String nome, int cpf, int rg, String endereco, Date dt_nascimento) {
        this.nome = nome;
        this.cpf = cpf;
        this.rg = rg;
        this.endereco = endereco;
        this.dt_nascimento = dt_nascimento;
    }

     
     public Short getId() {
        return id;
    }

    public void setId(Short id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public int getCpf() {
        return cpf;
    }

    public void setCpf(int cpf) {
        this.cpf = cpf;
    }

    public int getRg() {
        return rg;
    }

    public void setRg(int rg) {
        this.rg = rg;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public String getEndereco() {
        return endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    public Date getDt_nascimento() {
        return dt_nascimento;
    }

    public void setDt_nascimento(Date dt_nascimento) {
        this.dt_nascimento = dt_nascimento;
    }
     
}


